### ISSUE TITLE
Texture crassh

### ISSUE THREAD

**Issue by LunarNym** [l33tmaan/ACulinaryArtillery---.NET7#27]
Having a rash related to a missing texture for pie crust. Error report:

04/06/2024 17:36:24: Critical error occurred
Loaded Mods: aculinaryartillery@1.1.4, tonwexp@1.1.0, trophies@1.0.0, bds@1.0.0, bettercrates@1.7.1, betterdrifters@2.1.3, bettershears@1.0.0, buzzwords@1.7.0, cavecontent@1.0.1, cellardoor@1.4.0, Ceramos@0.5.1, chiseltools@1.11.6, ClaimsRadar@1.1.0, crazyskincustomization@1.0.0, decor@1.1.0, hqzlights@1.1.1, eldritchcuteclothing@1.0.2, entitiesinteract@1.0.9, extrachests@1.8.0, floralzonescaperegion@1.0.9, floralzonescaribbeanregion@1.0.6, floralzonescentralaustralianregion@1.0.4, floralzoneseastasiaticregion@1.0.2, floralzonesneozeylandicregion@1.0.2, flourbags@1.0.4, caninae@1.0.15, dinornithidae@0.3.0, machairodontinae@1.0.8, pantherinae@1.1.9, foundrymod@1.0.0, geodesandgemstones@1.1.1, geoaddons@1.3.4, HangingOilLamps@1.0.1, millwright@1.1.5, moreclay@1.0.2, MoreTorchHolders@1.0.0, nailsmold@1.0.1, pipeleaf@1.6.0, plantmat@1.7.3, primitivesurvival@3.5.5, roas@1.0.0, rope-bridges@1.1.0, rpvoicechat@2.3.9, spyglass@0.5.1, swordz@1.1.7, temporal_gears_stack@1.0.0, viescraftmachines@2.3.1, visibleore@1.0.1, game@1.19.8, abcsreborn@0.2.1, accessibilitytweaks@3.7.1, AgeOfConfession@2.0.4, alchemy@1.6.32, animalcages@3.0.2, animationmanagerlib@0.8.8, egocaribautomapmarkers@3.1.0, betterfirepit@1.1.4, betterjonasdevices@1.1.0, betterruins@0.3.5, blacksmithenhancements@1.0.5, butterflycases@1.0.1, canjewelry@0.2.31, canmarket@0.3.32, carryon@1.7.4, ColoredTorchesRedux@1.1.0, commonlib@2.3.7, composter@1.1.0, cooperativecombat@1.1.1, debarkedlogintofirewood@1.0.0, divisionoflabor@1.0.8, earlychiseling@1.0.1, expandedfoods@1.6.9, extrachutes@1.0.0, extrainfo@1.7.0, fairplayguardian@1.1.7, flowerfarming@1.1.0, fromgoldencombs@1.4.30, hangingbaskets@1.1.0, heatretention@1.0.2, hudclock@3.4.0, sailboat@1.3.0, justanarrowheadmold@1.0.1, leaderboards@1.1.2, maltiezbows@1.0.4, medievalexpansion@3.13.1, moreplaster@1.0.2, offhanddebuffpatch@0.5.0, outlawmod@1.2.3, pelaguswinds@1.0.0, playerlist@1.8.1, prospecttogether@1.3.0, rockstratavariety@0.0.1, rustboundmagic@1.9.33, simplecloth@1.0.2, sleepvote@1.0.7, spawnhighlight@1.2.0, stonebakeoven@1.1.3, stonerailings@1.2.2, storagecontroller@1.0.11, storageoptions@1.0.2, temporalstormtimer@1.1.1, th3dungeon@0.2.1, usefulstuff17@1.3.2, vehicleslib@1.0.1, vinconomy@0.2.7, creative@1.19.8, vsimgui@1.1.3, vsinstruments@1.2.7, survival@1.19.8, warmarmor@1.1.0, wildfarmingrevival@1.1.9, workbenchexpansion@1.8.0, xlib@0.8.3, bullseye-continued@2.5.8, configlib@1.3.13, em@2.6.0, extraoverlays@1.4.0, fsmlib@0.4.5, jonascyclezero@1.0.0-pre.1, playercorpse@1.10.1-rc.1, rifteye@0.3.6, stonequarry@3.2.1, vanity@2.1.2, xskills@0.8.5, bricklayers@2.5.3, madgnomeserver@0.2.24, maltiezcrossbows@0.3.10, maltiezfirearms@0.5.4, tailorsdelight@1.5.1, madgnomeservermod2@0.0.7
System.ArgumentNullException: Value cannot be null. (Parameter 'Unable to find a texture for texture code 'dough' in pie. Giving up. Sorry.')
   at Vintagestory.Client.NoObf.ShapeTesselator.TesselateShapeElement(Int32 indexForLogging, MeshData meshdata, ShapeElement element, TesselationMetaData meta) in VintagestoryLib\Client\Render\Tesselation\ShapeTesselator.cs:line 394
   at Vintagestory.Client.NoObf.ShapeTesselator.TesselateShapeElements(MeshData meshdata, ShapeElement[] elements, TesselationMetaData meta) in VintagestoryLib\Client\Render\Tesselation\ShapeTesselator.cs:line 306
   at Vintagestory.Client.NoObf.ShapeTesselator.TesselateShapeElements(MeshData meshdata, ShapeElement[] elements, TesselationMetaData meta) in VintagestoryLib\Client\Render\Tesselation\ShapeTesselator.cs:line 306
   at Vintagestory.Client.NoObf.ShapeTesselator.TesselateShape(Shape shapeBase, MeshData& modeldata, Vec3f wholeMeshRotation, Vec3f wholeMeshOffset, Single wholeMeshScale, TesselationMetaData meta) in VintagestoryLib\Client\Render\Tesselation\ShapeTesselator.cs:line 302
   at Vintagestory.GameContent.MealMeshCache.GetPieMesh(ItemStack pieStack, ModelTransform transform) in VSSurvivalMod\Systems\Cooking\MealMeshCache.cs:line 239
   at Vintagestory.GameContent.MealMeshCache.GetOrCreatePieMeshRef(ItemStack pieStack) in VSSurvivalMod\Systems\Cooking\MealMeshCache.cs:line 133
   at Vintagestory.GameContent.BlockPie.OnBeforeRender(ICoreClientAPI capi, ItemStack itemstack, EnumItemRenderTarget target, ItemRenderInfo& renderinfo) in VSSurvivalMod\Block\BlockPie.cs:line 206
   at Vintagestory.Client.NoObf.InventoryItemRenderer.GetItemStackRenderInfo(ClientMain game, ItemSlot inSlot, EnumItemRenderTarget target, Single dt) in VintagestoryLib\Client\Render\InventoryItemRenderer.cs:line 315
   at Vintagestory.Client.NoObf.InventoryItemRenderer.RenderItemstackToGui(ItemSlot inSlot, Double posX, Double posY, Double posZ, Single size, Int32 color, Single dt, Boolean shading, Boolean origRotate, Boolean showStackSize) in VintagestoryLib\Client\Render\InventoryItemRenderer.cs:line 194
   at Vintagestory.API.Client.GuiElementItemSlotGridBase.RenderInteractiveElements(Single deltaTime) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Inventory\GuiElementItemSlotGridBase.cs:line 509
   at Vintagestory.API.Client.GuiComposer.Render(Single deltaTime) in VintagestoryApi\Client\UI\GuiComposer.cs:line 716
   at Vintagestory.API.Client.GuiDialog.OnRenderGUI(Single deltaTime) in VintagestoryApi\Client\UI\Dialog\GuiDialog.cs:line 385
   at Vintagestory.API.Client.GuiDialogBlockEntity.OnRenderGUI(Single deltaTime) in VintagestoryApi\Client\UI\Dialog\GuiDialogBlockEntity.cs:line 111
   at Vintagestory.Client.NoObf.GuiManager.OnRenderFrameGUI(Single deltaTime) in VintagestoryLib\Client\Systems\Gui\GuiManager.cs:line 318
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 186
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 809
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 1013
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 676
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 651
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 324
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries for Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 21/05/2024 00:01:05, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.8.0, time stamp: 0x661e0000
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process ID: 0x0x4918
Faulting application start time: 0x0x1daab056e77fa93
Faulting application path: D:\Games\Vintagestory\Vintagestory.exe
Faulting module path: D:\Games\Vintagestory\Lib\openal32.dll
Report ID: d6df9a0e-e0fa-41b4-993e-079747b24181
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 21/05/2024 00:00:48, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.8.0, time stamp: 0x661e0000
Faulting module name: KERNELBASE.dll, version: 10.0.22621.3527, time stamp: 0x83efbeab
Exception code: 0xe0434352
Fault offset: 0x000000000006543c
Faulting process ID: 0x0x4918
Faulting application start time: 0x0x1daab056e77fa93
Faulting application path: D:\Games\Vintagestory\Vintagestory.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report ID: 7ab7ad3b-40bd-49b2-b475-678c154d46a3
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 20/05/2024 23:31:12, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.8.0, time stamp: 0x661e0000
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process ID: 0x0x2c84
Faulting application start time: 0x0x1daaae10e72cb76
Faulting application path: D:\Games\Vintagestory\Vintagestory.exe
Faulting module path: D:\Games\Vintagestory\Lib\openal32.dll
Report ID: ff2955f1-5156-4fc9-85fe-a69381c6ef9a
Faulting package full name: 
Faulting package-relative application ID:  }

**Comment by l33tmaan** [comment]
Try downloading the 1.2.2 update and let me know if this still happens.
