### ISSUE TITLE
Right-Clicking on sunflower seeds with bowl inside mixing bowl crashes game

### ISSUE THREAD

**Issue by TheAleWu** [l33tmaan/ACulinaryArtillery---.NET7#28]
Steps to reproduce:

1. Open mixing bowl
2. Put sunflower seeds in slot
3. Right click with bowl on it

```
Running on 64 bit Windows 10.0.22631.0 with 32638 MB RAM
Game Version: v1.19.8 (Stable)
08.06.2024 23:15:31: Critical error occurred
Loaded Mods: aculinaryartillery@1.1.5, bettercrates@1.7.1, chiseltools@1.12.1, jackofalltraits@1.0.0, juicyores@1.0.0, millwright@1.1.5, moreicons_cs@1.1.0, MoreTorchHolders@1.0.0, primitivesurvival@3.5.5, qptech@1.15.1, split-that-chest@1.0.0, volumetricshadingreupdated@0.7.5, game@1.19.8, abcsreborn@0.2.1, blacksmithgloves@1.0.1, commonlib@2.3.7, divisionoflabor@1.0.8, electricity@0.0.11, expandedfoods@1.6.9, herbarium@1.2.0, hudclock@3.4.0, prospecttogether@1.3.0, scythemold@1.0.1, sticksfromfirewood-alewu@1.0.0, storagecontroller@1.0.11, temporalsmithing@0.2.2, vtpp@1.1.1, creative@1.19.8, vsinstruments@1.2.7, survival@1.19.8, wildfarmingrevival@1.1.9, xlib@0.8.5-pre.1, stonequarry@3.2.1, wildcraftfruit@1.2.1, wildcraftherb@0.0.1, wildcrafttree@1.1.0, xskills@0.8.7-pre.1
System.NullReferenceException: Object reference not set to an instance of an object.
   at ACulinaryArtillery.ItemSlotMixingBowl.ActivateSlotRightClick_Patch1(ItemSlotMixingBowl this, ItemSlot sourceSlot, ItemStackMoveOperation& op)
   at Vintagestory.API.Common.ItemSlot.ActivateSlot(ItemSlot sourceSlot, ItemStackMoveOperation& op) in VintagestoryApi\Common\Inventory\ItemSlot.cs:line 297
   at Vintagestory.API.Common.InventoryBase.ActivateSlot(Int32 slotId, ItemSlot sourceSlot, ItemStackMoveOperation& op) in VintagestoryApi\Common\Inventory\InventoryBase.cs:line 453
   at Vintagestory.API.Client.GuiElementItemSlotGridBase.SlotClick(ICoreClientAPI api, Int32 slotId, EnumMouseButton mouseButton, Boolean shiftPressed, Boolean ctrlPressed, Boolean altPressed) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Inventory\GuiElementItemSlotGridBase.cs:line 978
   at Vintagestory.API.Client.GuiElementItemSlotGridBase.OnMouseDownOnElement(ICoreClientAPI api, MouseEvent args) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Inventory\GuiElementItemSlotGridBase.cs:line 771
   at Vintagestory.API.Client.GuiComposer.OnMouseDown(MouseEvent mouseArgs) in VintagestoryApi\Client\UI\GuiComposer.cs:line 494
   at Vintagestory.API.Client.GuiDialog.OnMouseDown(MouseEvent args) in VintagestoryApi\Client\UI\Dialog\GuiDialog.cs:line 560
   at Vintagestory.Client.NoObf.GuiManager.OnMouseDown(MouseEvent args) in VintagestoryLib\Client\Systems\Gui\GuiManager.cs:line 390
   at Vintagestory.Client.NoObf.ClientMain.UpdateMouseButtonState(EnumMouseButton button, Boolean down) in VintagestoryLib\Client\ClientMain.cs:line 1919
   at Vintagestory.Client.HotkeyManager.TriggerHotKey(KeyEvent keyEventargs, IWorldAccessor world, IPlayer player, Boolean allowCharacterControls, Boolean isGlobal, Boolean fallBack, Boolean keyup) in VintagestoryLib\Client\HotkeyManager.cs:line 431
   at Vintagestory.Client.HotkeyManager.OnMouseButton(ClientMain game, EnumMouseButton button, Int32 modifiers, Boolean buttonDown) in VintagestoryLib\Client\HotkeyManager.cs:line 576
   at Vintagestory.Client.NoObf.ClientMain.OnMouseDownRaw(MouseEvent args) in VintagestoryLib\Client\ClientMain.cs:line 1862
   at Vintagestory.Client.GuiScreenRunningGame.OnMouseDown(MouseEvent args) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 329
   at Vintagestory.Client.ScreenManager.OnMouseDown(MouseEvent e) in VintagestoryLib\Client\ScreenManager.cs:line 882
   at Vintagestory.Client.NoObf.ClientPlatformWindows.Mouse_ButtonDown(MouseButtonEventArgs e) in VintagestoryLib\Client\ClientPlatform\Input.cs:line 201
   at OpenTK.Windowing.Desktop.NativeWindow.OnMouseDown(MouseButtonEventArgs e)
   at OpenTK.Windowing.Desktop.NativeWindow.MouseButtonCallback(Window* window, MouseButton button, InputAction action, KeyModifiers mods)
--- End of stack trace from previous location ---
   at OpenTK.Windowing.Desktop.NativeWindow.RethrowCallbackExceptionsIfNeeded()
   at OpenTK.Windowing.Desktop.NativeWindow.ProcessWindowEvents(Boolean waitForEvents)
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 324
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

```

**Comment by l33tmaan** [comment]
Try downloading the 1.2.2 update and let me know if this still happens.
