### ISSUE TITLE
Client Crash on Server Join

### ISSUE THREAD

**Issue by NiemandNatural** [l33tmaan/ACulinaryArtillery---.NET7#30]
Am ServerAdmin.
Been away for 36 hours, maybe something spoiled in my inv/hand.
Client Crashes onServerJoin:

```Running on 64 bit Windows 10.0.19045.0 with 65456 MB RAM
Game Version: v1.19.8 (Stable)
02.08.2024 12:25:05: Critical error occurred in the following mod: aculinaryartillery@1.1.5
Loaded Mods: tadmorecharcoal@1.0.0, aculinaryartillery@1.1.5, bettercrates@1.7.0, chiseltools@1.12.3, ClaimsRadar@1.1.0, decor@1.1.1, entitiesinteract@1.0.11, capreolinae@1.1.5, foundrymod@1.0.0, HangingOilLamps@1.0.1, immersivecorpsedrop@1.0.2, millwright@1.1.6, moredrygrass@0.2.0, palisademod@1.1.0, primitivesurvival@3.6.1, quicklimepk@1.0.0, rpvoicechat@2.3.9, spyglass@0.5.1, steelbit1499@0.0.1, swordz@1.1.8, usefuldrifterloot@1.1.0, vintariaclasses@0.0.7, visibleore@1.0.1, game@1.19.8, ancienttools@1.5.18, animationmanagerlib@0.8.8, augplantlib@0.0.3, betterruins@0.3.7, butchering@1.6.5, carryon@1.7.4, coinage@1.10.2, commonlib@2.5.0-rc.2, danatweaks@2.3.0, extrainfo@1.7.0, fairplayguardian@1.1.7, fromgoldencombs@1.5.1, herbarium@1.2.0, hydrateordiedrate@1.1.6, lib2d@1.0.0, medievalexpansion@3.13.1, morepiles@1.5.0, pelaguswinds@1.0.0, petai@2.2.6, playerlist@2.1.2, prospecttogether@1.3.0, rivers@3.1.0, sailboat@1.3.1, somethinginthewater@1.2.4, stonebakeoven@1.1.3, storageoptions@1.0.2, th3dungeon@0.2.1, trailmod@1.0.8, vanvar@5.0.3, vinconomy@0.3.0, creative@1.19.8, vsimgui@1.1.5, vsserverpanel@0.1.5, survival@1.19.8, wildfarmingrevival@1.2.2, xlib@0.8.6, bullseye-continued@2.5.8, cats@2.0.3, configlib@1.3.13, em@2.6.3, extraoverlays@1.4.0, feverstonehorses@1.6.1, newworldcrops@0.0.8, playercorpse@1.10.1-rc.1, stonequarry@3.3.1, wildcraftfruit@1.2.1, wildcrafttree@1.1.0, wolftaming@2.1.3, xskills@0.8.8, bricklayers@2.5.6, moreroads@1.5.7, statushudcont@2.1.1
System.NullReferenceException: Object reference not set to an instance of an object.
   at ACulinaryArtillery.ItemExpandedRawFood.GenMesh(ITextureAtlasAPI targetAtlas, String[] ings, Vec3f rot, ITesselatorAPI tesselator)
   at ACulinaryArtillery.ItemExpandedRawFood.OnBeforeRender(ICoreClientAPI capi, ItemStack itemstack, EnumItemRenderTarget target, ItemRenderInfo& renderinfo)
   at Vintagestory.Client.NoObf.InventoryItemRenderer.GetItemStackRenderInfo(ClientMain game, ItemSlot inSlot, EnumItemRenderTarget target, Single dt) in VintagestoryLib\Client\Render\InventoryItemRenderer.cs:line 387
   at Vintagestory.Client.NoObf.InventoryItemRenderer.RenderItemstackToGui(ItemSlot inSlot, Double posX, Double posY, Double posZ, Single size, Int32 color, Single dt, Boolean shading, Boolean origRotate, Boolean showStackSize) in VintagestoryLib\Client\Render\InventoryItemRenderer.cs:line 195
   at Vintagestory.Client.NoObf.RenderAPIGame.RenderItemstackToGui(ItemSlot inSlot, Double posX, Double posY, Double posZ, Single size, Int32 color, Single dt, Boolean shading, Boolean rotate, Boolean showStackSize) in VintagestoryLib\Client\API\RenderAPIGame.cs:line 268
   at Vintagestory.API.Client.GuiElementItemSlotGridBase.RenderInteractiveElements(Single deltaTime) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Inventory\GuiElementItemSlotGridBase.cs:line 479
   at Vintagestory.API.Client.GuiComposer.Render(Single deltaTime) in VintagestoryApi\Client\UI\GuiComposer.cs:line 716
   at Vintagestory.API.Client.GuiDialog.OnRenderGUI(Single deltaTime) in VintagestoryApi\Client\UI\Dialog\GuiDialog.cs:line 381
   at Vintagestory.API.Client.HudElement.OnRenderGUI(Single deltaTime) in VintagestoryApi\Client\UI\HudElement.cs:line 30
   at Vintagestory.Client.NoObf.HudHotbar.OnRenderGUI(Single deltaTime) in VintagestoryLib\Client\Systems\Gui\Huds\HudHotbar.cs:line 575
   at Vintagestory.Client.NoObf.GuiManager.OnRenderFrameGUI(Single deltaTime) in VintagestoryLib\Client\Systems\Gui\GuiManager.cs:line 301
   at Vintagestory.API.Client.DummyRenderer.OnRenderFrame(Single deltaTime, EnumRenderStage stage) in VintagestoryApi\Client\API\IClientEventAPI.cs:line 83
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 192
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 806
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 995
   at Vintagestory.Client.GuiScreenRunningGame.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 241
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 676
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 651
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 324
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries for Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 28.07.2024 12:58:27, Site = , Source = Application Error, Message = Name der fehlerhaften Anwendung: Vintagestory.exe, Version: 1.19.8.0, Zeitstempel: 0x661e0000
Name des fehlerhaften Moduls: openal32.dll, Version: 1.23.0.0, Zeitstempel: 0x63dd31ad
Ausnahmecode: 0x40000015
Fehleroffset: 0x00000000000df046
ID des fehlerhaften Prozesses: 0x425c
Startzeit der fehlerhaften Anwendung: 0x01dae0d798d5df8c
Pfad der fehlerhaften Anwendung: G:\Vintagestory19\Vintagestory.exe
Pfad des fehlerhaften Moduls: G:\Vintagestory19\Lib\openal32.dll
Berichtskennung: 3099f748-4bb0-4762-aeea-c70654573dce
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist:  }
--------------
{ TimeGenerated = 28.07.2024 12:58:12, Site = , Source = Application Error, Message = Name der fehlerhaften Anwendung: Vintagestory.exe, Version: 1.19.8.0, Zeitstempel: 0x661e0000
Name des fehlerhaften Moduls: KERNELBASE.dll, Version: 10.0.19041.4648, Zeitstempel: 0x5a4af933
Ausnahmecode: 0xe0434352
Fehleroffset: 0x000000000003b699
ID des fehlerhaften Prozesses: 0x425c
Startzeit der fehlerhaften Anwendung: 0x01dae0d798d5df8c
Pfad der fehlerhaften Anwendung: G:\Vintagestory19\Vintagestory.exe
Pfad des fehlerhaften Moduls: C:\Windows\System32\KERNELBASE.dll
Berichtskennung: 2576a165-7f10-4cc4-a385-bf6e2cb46d8f
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist:  }
--------------
{ TimeGenerated = 28.07.2024 12:18:48, Site = , Source = Application Error, Message = Name der fehlerhaften Anwendung: Vintagestory.exe, Version: 1.19.8.0, Zeitstempel: 0x661e0000
Name des fehlerhaften Moduls: KERNELBASE.dll, Version: 10.0.19041.4648, Zeitstempel: 0x5a4af933
Ausnahmecode: 0xe0434352
Fehleroffset: 0x000000000003b699
ID des fehlerhaften Prozesses: 0x2d8c
Startzeit der fehlerhaften Anwendung: 0x01dae0d726d00d2e
Pfad der fehlerhaften Anwendung: G:\Vintagestory19\Vintagestory.exe
Pfad des fehlerhaften Moduls: C:\Windows\System32\KERNELBASE.dll
Berichtskennung: 4483e0bb-e4a8-42cb-b57f-3af80459af26
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist:  }```

**Comment by NiemandNatural** [comment]
Emptied my inventory.

Still crashing a few (1-5) minutes after logging in, while my inventory is empty and while I'm tabbed out:
`Running on 64 bit Windows 10.0.19045.0 with 65456 MB RAM
Game Version: v1.19.8 (Stable)
02.08.2024 20:59:43: Critical error occurred in the following mod: aculinaryartillery@1.1.5
Loaded Mods: tadmorecharcoal@1.0.0, aculinaryartillery@1.1.5, bettercrates@1.7.0, chiseltools@1.12.3, ClaimsRadar@1.1.0, decor@1.1.1, entitiesinteract@1.0.11, capreolinae@1.1.5, foundrymod@1.0.0, HangingOilLamps@1.0.1, immersivecorpsedrop@1.0.2, millwright@1.1.6, moredrygrass@0.2.0, palisademod@1.1.0, primitivesurvival@3.6.1, quicklimepk@1.0.0, rpvoicechat@2.3.9, spyglass@0.5.1, steelbit1499@0.0.1, swordz@1.1.8, usefuldrifterloot@1.1.0, vintariaclasses@0.0.7, visibleore@1.0.1, game@1.19.8, ancienttools@1.5.18, animationmanagerlib@0.8.8, augplantlib@0.0.3, betterruins@0.3.7, butchering@1.6.5, carryon@1.7.4, coinage@1.10.2, commonlib@2.5.0-rc.2, danatweaks@2.3.0, extrainfo@1.7.0, fairplayguardian@1.1.7, fromgoldencombs@1.5.1, herbarium@1.2.0, hydrateordiedrate@1.1.6, lib2d@1.0.0, medievalexpansion@3.13.1, morepiles@1.5.0, pelaguswinds@1.0.0, petai@2.2.6, playerlist@2.1.2, prospecttogether@1.3.0, rivers@3.1.0, sailboat@1.3.1, somethinginthewater@1.2.4, stonebakeoven@1.1.3, storageoptions@1.0.2, th3dungeon@0.2.1, trailmod@1.0.8, vanvar@5.0.3, vinconomy@0.3.0, creative@1.19.8, vsimgui@1.1.5, vsserverpanel@0.1.5, survival@1.19.8, wildfarmingrevival@1.2.2, xlib@0.8.6, bullseye-continued@2.5.8, cats@2.0.3, configlib@1.3.13, em@2.6.3, extraoverlays@1.4.0, feverstonehorses@1.6.1, newworldcrops@0.0.8, playercorpse@1.10.1-rc.1, stonequarry@3.3.1, wildcraftfruit@1.2.1, wildcrafttree@1.1.0, wolftaming@2.1.3, xskills@0.8.8, bricklayers@2.5.6, moreroads@1.5.7, statushudcont@2.1.1
System.NullReferenceException: Object reference not set to an instance of an object.
   at ACulinaryArtillery.ItemExpandedRawFood.GenMesh(ITextureAtlasAPI targetAtlas, String[] ings, Vec3f rot, ITesselatorAPI tesselator)
   at ACulinaryArtillery.ItemExpandedRawFood.OnBeforeRender(ICoreClientAPI capi, ItemStack itemstack, EnumItemRenderTarget target, ItemRenderInfo& renderinfo)
   at Vintagestory.Client.NoObf.InventoryItemRenderer.GetItemStackRenderInfo(ClientMain game, ItemSlot inSlot, EnumItemRenderTarget target, Single dt) in VintagestoryLib\Client\Render\InventoryItemRenderer.cs:line 315
   at Vintagestory.GameContent.EntityShapeRenderer.RenderHeldItem_Patch1(EntityShapeRenderer this, Single dt, Boolean isShadowPass, Boolean right)
   at Vintagestory.GameContent.EntityPlayerShapeRenderer.DoRender3DOpaque_Patch1(EntityPlayerShapeRenderer this, Single dt, Boolean isShadowPass)
   at Vintagestory.Client.NoObf.SystemRenderEntities.OnRenderFrameShadows(Single dt) in VintagestoryLib\Client\Systems\Render\RenderEntities.cs:line 164
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 186
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 809
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 815
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 731
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 200
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 676
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 651
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 324
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries for Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 28.07.2024 12:58:27, Site = , Source = Application Error, Message = Name der fehlerhaften Anwendung: Vintagestory.exe, Version: 1.19.8.0, Zeitstempel: 0x661e0000
Name des fehlerhaften Moduls: openal32.dll, Version: 1.23.0.0, Zeitstempel: 0x63dd31ad
Ausnahmecode: 0x40000015
Fehleroffset: 0x00000000000df046
ID des fehlerhaften Prozesses: 0x425c
Startzeit der fehlerhaften Anwendung: 0x01dae0d798d5df8c
Pfad der fehlerhaften Anwendung: G:\Vintagestory19\Vintagestory.exe
Pfad des fehlerhaften Moduls: G:\Vintagestory19\Lib\openal32.dll
Berichtskennung: 3099f748-4bb0-4762-aeea-c70654573dce
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist:  }
--------------
{ TimeGenerated = 28.07.2024 12:58:12, Site = , Source = Application Error, Message = Name der fehlerhaften Anwendung: Vintagestory.exe, Version: 1.19.8.0, Zeitstempel: 0x661e0000
Name des fehlerhaften Moduls: KERNELBASE.dll, Version: 10.0.19041.4648, Zeitstempel: 0x5a4af933
Ausnahmecode: 0xe0434352
Fehleroffset: 0x000000000003b699
ID des fehlerhaften Prozesses: 0x425c
Startzeit der fehlerhaften Anwendung: 0x01dae0d798d5df8c
Pfad der fehlerhaften Anwendung: G:\Vintagestory19\Vintagestory.exe
Pfad des fehlerhaften Moduls: C:\Windows\System32\KERNELBASE.dll
Berichtskennung: 2576a165-7f10-4cc4-a385-bf6e2cb46d8f
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist:  }
--------------
{ TimeGenerated = 28.07.2024 12:18:48, Site = , Source = Application Error, Message = Name der fehlerhaften Anwendung: Vintagestory.exe, Version: 1.19.8.0, Zeitstempel: 0x661e0000
Name des fehlerhaften Moduls: KERNELBASE.dll, Version: 10.0.19041.4648, Zeitstempel: 0x5a4af933
Ausnahmecode: 0xe0434352
Fehleroffset: 0x000000000003b699
ID des fehlerhaften Prozesses: 0x2d8c
Startzeit der fehlerhaften Anwendung: 0x01dae0d726d00d2e
Pfad der fehlerhaften Anwendung: G:\Vintagestory19\Vintagestory.exe
Pfad des fehlerhaften Moduls: C:\Windows\System32\KERNELBASE.dll
Berichtskennung: 4483e0bb-e4a8-42cb-b57f-3af80459af26
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist:  }`

**Comment by NiemandNatural** [comment]
Reinstall (including deleting Cache and ModsByServer), fixed it.

**Comment by l33tmaan** [comment]
It was probably the modCache that was the issue. We've seen that clearing it out can fix these problems.
