### ISSUE TITLE
Crash Opening Container After EF 1.7.0 Update

### ISSUE THREAD

**Issue by splitlungs** [l33tmaan/ACulinaryArtillery---.NET7#33]
Updated to most recent Expanded Foods and I'm getting a crash when opening a container with a few different Berry Bread (a few Charred), Jugs of Gooseberry Juice and Gooseberry dry mash, and Cranberry dry mash.

When opening that container, I received this CTD error.

Thank You

```
Running on 64 bit Windows 10.0.19045.0 with 65445 MB RAM
Game Version: v1.19.8 (Stable)
8/21/2024 3:08:51 PM: Critical error occurred in the following mod: aculinaryartillery@1.1.5
Loaded Mods: aculinaryartillery@1.1.5, balancedthirst@0.0.37, chiseltools@1.12.3, fantasycreatures@0.7.1, hideandfabric@1.3.0, OresAPlenty@3.2.0, primitivesurvival@3.6.4, rpvoicechat@2.3.9, swordz@1.1.8, translocatorengineeringredux@1.5.1, game@1.19.8, betterruins@0.3.7, commonlib@2.3.7, herbarium@1.2.0, krpgenchantment@0.3.8, krpgwands@0.2.1, medievalexpansion@3.13.1, onebedsleeping@2.4.1, petai@2.2.6, spawnersapi@1.0.8, storagecontroller@1.0.11, vanvar@5.0.4, creative@1.19.8, survival@1.19.8, xlib@0.8.6, battletowers@1.0.3, cats@2.0.3, feverstonewilds@1.5.0-rc.2, foxtaming@1.4.0, playercorpse@1.10.1-rc.1, wildcraftfruit@1.2.1, wildcrafttree@1.1.0, wolftaming@2.1.3, xskills@0.8.8
System.NullReferenceException: Object reference not set to an instance of an object.
   at ACulinaryArtillery.ItemExpandedRawFood.GenMesh(ITextureAtlasAPI targetAtlas, String[] ings, Vec3f rot, ITesselatorAPI tesselator)
   at ACulinaryArtillery.ItemExpandedRawFood.OnBeforeRender(ICoreClientAPI capi, ItemStack itemstack, EnumItemRenderTarget target, ItemRenderInfo& renderinfo)
   at Vintagestory.Client.NoObf.InventoryItemRenderer.GetItemStackRenderInfo(ClientMain game, ItemSlot inSlot, EnumItemRenderTarget target, Single dt) in VintagestoryLib\Client\Render\InventoryItemRenderer.cs:line 315
   at Vintagestory.Client.NoObf.InventoryItemRenderer.RenderItemstackToGui(ItemSlot inSlot, Double posX, Double posY, Double posZ, Single size, Int32 color, Single dt, Boolean shading, Boolean origRotate, Boolean showStackSize) in VintagestoryLib\Client\Render\InventoryItemRenderer.cs:line 194
   at Vintagestory.API.Client.GuiElementItemSlotGridBase.RenderInteractiveElements(Single deltaTime) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Inventory\GuiElementItemSlotGridBase.cs:line 509
   at Vintagestory.API.Client.GuiComposer.Render(Single deltaTime) in VintagestoryApi\Client\UI\GuiComposer.cs:line 716
   at Vintagestory.API.Client.GuiDialog.OnRenderGUI(Single deltaTime) in VintagestoryApi\Client\UI\Dialog\GuiDialog.cs:line 385
   at Vintagestory.API.Client.GuiDialogBlockEntity.OnRenderGUI(Single deltaTime) in VintagestoryApi\Client\UI\Dialog\GuiDialogBlockEntity.cs:line 112
   at Vintagestory.Client.NoObf.GuiManager.OnRenderFrameGUI(Single deltaTime) in VintagestoryLib\Client\Systems\Gui\GuiManager.cs:line 318
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 186
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 809
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 1013
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 676
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 651
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 324
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries for Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 8/5/2024 4:15:33 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.8.0, time stamp: 0x661e0000
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x593c
Faulting application start time: 0x01dae77c0fba82c4
Faulting application path: C:\Users\radmin\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\Users\radmin\AppData\Roaming\Vintagestory\Lib\openal32.dll
Report Id: cfbbff55-9584-4856-a480-7f97b5cb35dc
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 8/5/2024 4:15:18 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.8.0, time stamp: 0x661e0000
Faulting module name: KERNELBASE.dll, version: 10.0.19041.4648, time stamp: 0x5a4af933
Exception code: 0xe0434352
Fault offset: 0x000000000003b699
Faulting process id: 0x593c
Faulting application start time: 0x01dae77c0fba82c4
Faulting application path: C:\Users\radmin\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: 00af29e0-8879-4b8a-b51f-c78357e38920
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 8/2/2024 9:21:31 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.8.0, time stamp: 0x661e0000
Faulting module name: unknown, version: 0.0.0.0, time stamp: 0x00000000
Exception code: 0xc0000005
Fault offset: 0x00007ffb4be08235
Faulting process id: 0x981c
Faulting application start time: 0x01dae54bc816f313
Faulting application path: C:\Users\radmin\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: unknown
Report Id: 385c900e-f268-4a6c-8617-6e5b7ac41e6a
Faulting package full name: 
Faulting package-relative application ID:  }
```

**Comment by l33tmaan** [comment]
Try downloading the 1.2.2 update and let me know if this still happens.
