### ISSUE TITLE
Game crashes after interacting with Stormsoul Slop filled pie with a bottle in hand.

### ISSUE THREAD

**Issue by Kwehlani** [l33tmaan/ACulinaryArtillery---.NET7#40]
As the title states, my game crashes after interacting with a filled, or partially filled, Stormsoul Slop pie.

I tried creating one of these pies to diagnose an incompatibility with the Gourmand mod, and found that my game fully closed after I accidentally used an empty bottle on the unbaked pie. I don't see this as being a massive issue, but wanted to bring it to your attention in case creating these pies could be used to maliciously crash other players' games.

Running on 64 bit Windows 10.0.22631.0 with 32693 MB RAM
Game Version: v1.19.8 (Stable)
2024-10-02 12:32:25 AM: Critical error occurred in the following mod: aculinaryartillery@1.2.1
Loaded Mods: aculinaryartillery@1.2.1, game@1.19.8, expandedfoods@1.7.1, gourmand@1.2.2, creative@1.19.8, survival@1.19.8
System.NullReferenceException: Object reference not set to an instance of an object.
   at ACulinaryArtillery.BlockEntityPiePatch.mulitPie(Boolean& __result, InventoryBase& ___inv, BlockEntityPie __instance, ItemSlot slot, IPlayer byPlayer)
   at Vintagestory.GameContent.BlockEntityPie.TryAddIngredientFrom_Patch1(BlockEntityPie this, ItemSlot slot, IPlayer byPlayer)
   at Vintagestory.GameContent.BlockEntityPie.OnInteract(IPlayer byPlayer) in VSSurvivalMod\BlockEntity\BEPie.cs:line 169
   at Vintagestory.GameContent.BlockPie.OnBlockInteractStart(IWorldAccessor world, IPlayer byPlayer, BlockSelection blockSel) in VSSurvivalMod\Block\BlockPie.cs:line 494
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.TryBeginUseBlock(Block selectedBlock, BlockSelection blockSelection) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 864
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.HandleMouseInteractionsBlockSelected(Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 444
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.OnFinalizeFrame(Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 89
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 186
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 809
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 1013
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 676
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 651
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 324
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

**Comment by l33tmaan** [comment]
Try downloading the 1.2.2 update and let me know if this still happens.

**Comment by l33tmaan** [comment]
I can't replicate this anymore and it should be fixed. Closing this out.
