### ISSUE TITLE
Crashed on a 1.20.0-pre.9 test server

### ISSUE THREAD

**Issue by WickedSchnitzel** [l33tmaan/ACulinaryArtillery---.NET7#44]
Running on 64 bit Windows 10.0.19045.0 with 32723 MB RAM
Game Version: v1.20.0-pre.9 (Unstable)
03.11.2024 09:23:59: Critical error occurred in the following mod: aculinaryartillery@1.2.1
Loaded Mods: aculinaryartillery@1.2.1, ancientarmory@1.0.5, bettercrates@1.7.1, chiseltools@1.12.10, decor@1.1.6, extrachests@1.8.0, fantasycreatures@0.7.1, fixedpaths@1.0.1, pantherinae@1.1.12, foundrymod@1.0.0, moreicons_cs@1.1.0, primitivesurvival@3.7.0, nvscaffolding@1.0.1, translocatorengineeringredux@1.5.4, game@1.20.0-pre.9, weaponpackalphaunoff@1.5.1, animalcages@3.0.3, betterruins@0.3.7, butterflycases@1.0.1, carryon@1.8.0-pre.1, commonlib@2.5.0-rc.2, decayingcreatures@0.0.8, expandedfoods@1.7.2, fairplayguardian@1.1.7, furniturelibrary@1.0.13, heatretention@1.0.2, playerlist@2.1.4, simplefootstepsredux@1.0.1, sleepvote@1.0.7, tentbag@2.1.3, thecritterpack@0.9.1, vanity@2.2.1, vinconomy@0.3.4, creative@1.20.0-pre.9, vsquest@1.2.0, vsserverpanel@0.1.5, survival@1.20.0-pre.9, cob2@1.6.8, cobserver@1.0.2, em@3.0.0-pre.1, outerspacetunesvolume1@1.0.2, outerspacetunesvolume2@1.0.2, playercorpse@1.10.1-rc.1, rifteye@0.3.7, stonequarry@3.4.0, cob@1.9.9, outerspacetunesmaster@1.0.2
System.MissingMethodException: Method not found: 'Vintagestory.API.Common.IAsset Vintagestory.API.Common.IAssetManager.TryGet(System.String, Boolean)'.
   at ACulinaryArtillery.BlockBottle.GenMesh(ICoreClientAPI capi, ItemStack contentStack, BlockPos forBlockPos)
   at ACulinaryArtillery.BlockBottle.OnBeforeRender(ICoreClientAPI capi, ItemStack itemstack, EnumItemRenderTarget target, ItemRenderInfo& renderinfo)
   at Vintagestory.Client.NoObf.InventoryItemRenderer.GetItemStackRenderInfo(ClientMain game, ItemSlot inSlot, EnumItemRenderTarget target, Single dt) in VintagestoryLib\Client\Render\InventoryItemRenderer.cs:line 315
   at Vintagestory.Client.NoObf.InventoryItemRenderer.RenderItemstackToGui(ItemSlot inSlot, Double posX, Double posY, Double posZ, Single size, Int32 color, Single dt, Boolean shading, Boolean origRotate, Boolean showStackSize) in VintagestoryLib\Client\Render\InventoryItemRenderer.cs:line 194
   at Vintagestory.API.Client.GuiElementItemSlotGridBase.RenderInteractiveElements(Single deltaTime) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Inventory\GuiElementItemSlotGridBase.cs:line 512
   at Vintagestory.API.Client.GuiComposer.Render(Single deltaTime) in VintagestoryApi\Client\UI\GuiComposer.cs:line 718
   at Vintagestory.API.Client.GuiDialog.OnRenderGUI(Single deltaTime) in VintagestoryApi\Client\UI\Dialog\GuiDialog.cs:line 389
   at Vintagestory.Client.NoObf.GuiManager.OnRenderFrameGUI(Single deltaTime) in VintagestoryLib\Client\Systems\Gui\GuiManager.cs:line 318
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 186
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 819
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 1023
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 695
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 670
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 328
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass10_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 130
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries for Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 03.11.2024 02:35:32, Site = , Source = Application Error, Message = Name der fehlerhaften Anwendung: Vintagestory.exe, Version: 1.20.0.0, Zeitstempel: 0x66470000
Name des fehlerhaften Moduls: openal32.dll, Version: 1.23.0.0, Zeitstempel: 0x63dd31ad
Ausnahmecode: 0x40000015
Fehleroffset: 0x00000000000df046
ID des fehlerhaften Prozesses: 0x6148
Startzeit der fehlerhaften Anwendung: 0x01db2d9045e8057b
Pfad der fehlerhaften Anwendung: C:\Users\Kai\AppData\Roaming\Vintagestory\Vintagestory.exe
Pfad des fehlerhaften Moduls: C:\Users\Kai\AppData\Roaming\Vintagestory\Lib\openal32.dll
Berichtskennung: 193842fa-fa99-4464-9d50-0f11acce2b09
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist:  }
--------------
{ TimeGenerated = 03.11.2024 02:32:38, Site = , Source = Application Error, Message = Name der fehlerhaften Anwendung: Vintagestory.exe, Version: 1.20.0.0, Zeitstempel: 0x66470000
Name des fehlerhaften Moduls: openal32.dll, Version: 1.23.0.0, Zeitstempel: 0x63dd31ad
Ausnahmecode: 0x40000015
Fehleroffset: 0x00000000000df046
ID des fehlerhaften Prozesses: 0x2ac8
Startzeit der fehlerhaften Anwendung: 0x01db2d902926a42f
Pfad der fehlerhaften Anwendung: C:\Users\Kai\AppData\Roaming\Vintagestory\Vintagestory.exe
Pfad des fehlerhaften Moduls: C:\Users\Kai\AppData\Roaming\Vintagestory\Lib\openal32.dll
Berichtskennung: 3a0be5f8-3cb7-47eb-87ed-3435a93c45fe
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist:  }
--------------
{ TimeGenerated = 03.11.2024 02:28:08, Site = , Source = Application Error, Message = Name der fehlerhaften Anwendung: Vintagestory.exe, Version: 1.20.0.0, Zeitstempel: 0x66470000
Name des fehlerhaften Moduls: openal32.dll, Version: 1.23.0.0, Zeitstempel: 0x63dd31ad
Ausnahmecode: 0x40000015
Fehleroffset: 0x00000000000df046
ID des fehlerhaften Prozesses: 0xa14
Startzeit der fehlerhaften Anwendung: 0x01db2d8f780d323a
Pfad der fehlerhaften Anwendung: C:\Users\Kai\AppData\Roaming\Vintagestory\Vintagestory.exe
Pfad des fehlerhaften Moduls: C:\Users\Kai\AppData\Roaming\Vintagestory\Lib\openal32.dll
Berichtskennung: e650cb8d-d401-4872-85ec-d555ad3f06be
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist:  }

**Comment by WickedSchnitzel** [comment]
while entering "quest" into the creative inventory search bar.

**Comment by l33tmaan** [comment]
Works fine for me. Is this happening in 1.20.0-rc8?

![image](https://github.com/user-attachments/assets/cf2627b4-ecb5-4820-94a4-d1240e071e3a)

**Comment by l33tmaan** [comment]
Try downloading the 1.2.2 update and let me know if this still happens.
