### ISSUE TITLE
Crash when placing mixing bowl into world v1.2.1 VSv1.20.0.rc6

### ISSUE THREAD

**Issue by conventus-jkn** [l33tmaan/ACulinaryArtillery---.NET7#47]
After crafting the mixing bowl, as soon as I try to place it in the world on the floor game crashes:

Running on 64 bit Windows 10.0.22631.0 with 64729 MB RAM
Game Version: v1.20.0-rc.6 (Unstable)
27/12/2024 15:31:15: Critical error occurred in the following mod: aculinaryartillery@1.2.1
Loaded Mods: aculinaryartillery@1.2.1, bettercrates@1.8.0-rc.4, chiseltools@1.14.4, molds@0.1.3, nailsmold@1.0.2, noisybears@1.1.0, primitivesurvival@3.7.4, game@1.20.0-rc.6, blocksoverlay@4.0.2, carryon@1.8.0-pre.1, commonlib@2.6.1, expandedfoods@1.6.9, extrainfo@1.9.4, hudclockpatch@1.0.0, improvedhandbookrecipes@1.1.0, moreanimals@1.3.5, rivers@3.2.0, smithingplus@1.1.5, spawnhighlight@1.2.0, stepupadvanced@1.0.3, storagecontroller@1.1.2, creative@1.20.0-rc.6, survival@1.20.0-rc.6, wildfarmingrevival@1.3.3, xlibpatch@1.0.1, playercorpse@1.11.0, stonequarry@3.4.2, thriftysmithing@1.2.0, xskillspatch@1.0.4
System.MissingMethodException: Method not found: 'Vintagestory.API.Common.IAsset Vintagestory.API.Common.IAssetManager.TryGet(System.String, Boolean)'.
   at ACulinaryArtillery.BlockEntityMixingBowl.GenMesh(String type)
   at ACulinaryArtillery.BlockEntityMixingBowl.Initialize(ICoreAPI api)
   at Vintagestory.Client.NoObf.ClientWorldMap.SpawnBlockEntity(String classname, BlockPos position, ItemStack byItemStack) in VintagestoryLib\Client\ClientWorldMap.cs:line 1096
   at Vintagestory.Common.BlockAccessorBase.SpawnBlockEntity(String classname, BlockPos position, ItemStack byItemStack) in VintagestoryLib\Common\API\BlockAccessorBase.cs:line 627
   at Vintagestory.API.Common.Block.OnBlockPlaced(IWorldAccessor world, BlockPos blockPos, ItemStack byItemStack) in VintagestoryApi\Common\Collectible\Block\Block.cs:line 1333
   at Vintagestory.Common.BlockAccessorBase.SetSolidBlockInternal(Int32 blockId, BlockPos pos, IWorldChunk chunk, Boolean synchronize, Boolean relight, ItemStack byItemstack) in VintagestoryLib\Common\API\BlockAccessorBase.cs:line 153
   at Vintagestory.Common.BlockAccessorBase.SetBlockInternal(Int32 blockId, BlockPos pos, IWorldChunk chunk, Boolean synchronize, Boolean relight, Int32 layer, ItemStack byItemstack) in VintagestoryLib\Common\API\BlockAccessorBase.cs:line 115
   at Vintagestory.Common.BlockAccessorRelaxed.SetBlock(Int32 blockId, BlockPos pos, ItemStack byItemstack) in VintagestoryLib\Common\API\BlockAccessorRelaxed.cs:line 75
   at Vintagestory.API.Common.Block.DoPlaceBlock(IWorldAccessor world, IPlayer byPlayer, BlockSelection blockSel, ItemStack byItemStack) in VintagestoryApi\Common\Collectible\Block\Block.cs:line 928
   at Vintagestory.API.Common.Block.TryPlaceBlock(IWorldAccessor world, IPlayer byPlayer, ItemStack itemstack, BlockSelection blockSel, String& failureCode) in VintagestoryApi\Common\Collectible\Block\Block.cs:line 837
   at ACulinaryArtillery.BlockMixingBowl.TryPlaceBlock(IWorldAccessor world, IPlayer byPlayer, ItemStack itemstack, BlockSelection blockSel, String& failureCode)
   at Vintagestory.Client.NoObf.ClientMain.OnPlayerTryPlace(BlockSelection blockSelection, String& failureCode) in VintagestoryLib\Client\ClientMain.cs:line 1669
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.OnBlockBuild(BlockSelection blockSelection, Block onBlock, String& failureCode) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 708
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.HandleMouseInteractionsBlockSelected(Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 617
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.OnFinalizeFrame(Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 79
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 188
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 992
   at Vintagestory.Client.GuiScreenRunningGame.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 242
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 695
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 670
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 92
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 334
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass10_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 130
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

**Comment by conventus-jkn** [comment]
Also, the same problem with the Saucepan

**Comment by l33tmaan** [comment]
This isn't happening to me on 1.20.0-rc8. What happens if you turn your other mods off?

**Comment by l33tmaan** [comment]
Try downloading the 1.2.2 update we just put out and let me know if it still crashes.
