### ISSUE TITLE
Death Pie

### ISSUE THREAD

**Issue by scubamount** [l33tmaan/ACulinaryArtillery---.NET7#6]
Make pie, throw in water

18.8.2023 17:22:43 [Server Fatal] System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.API.Common.AssetLocation.ResolveToDomainAndPath(String domainAndPath, String& domain, String& path) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryApi\Common\Assets\AssetLocation.cs:line 169
   at Vintagestory.GameContent.BlockMeal.OnGroundIdle(EntityItem entityItem) in C:\Users\Tyron\Documents\vintagestory\game\VSSurvivalMod\Systems\Cooking\BlockMeal.cs:line 781
   at Vintagestory.API.Common.EntityItem.OnGameTick(Single dt) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryApi\Common\Entity\EntityItem.cs:line 150
   at Vintagestory.Server.ServerSystemEntitySimulation.TickEntities(Single dt) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Server\Systems\World\EntitySimulation.cs:line 326
   at Vintagestory.Server.ServerSystemEntitySimulation.OnServerTick(Single dt) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Server\Systems\World\EntitySimulation.cs:line 165
   at Vintagestory.Server.ServerMain.Process() in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Server\ServerMain.cs:line 849

**Comment by Dmitry221060** [comment]
I'm fairly certain that this is a problem with the main game. The game [tries to access](https://github.com/anegostudios/vssurvivalmod/blob/d1fed2053587ad4bec1fe4a6771d42d5cb29e760/Systems/Cooking/BlockMeal.cs#L805) "eatenBlock" attribute, but pies don't have it, which causes `NullReferenceException` down the line. 
You may want to make a bug report in the official discord channel and/or [this repo](https://github.com/anegostudios/VintageStory-Issues/issues).

**Comment by Dmitry221060** [comment]
Opened an issue in the official repo - anegostudios/VintageStory-Issues#3041. Further communication should be done there, while this issue can be closed as unrelated to the mod.
